version: '3'
services:
  database:
    image: postgres:latest
    env_file:
      - database.env
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
